name: Container image build and push to DockerHub

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - 'go.*'
      - '*.go'
      - '.github/workflows/docker.yaml'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'go.**'
      - '**.go'
      - '.github/workflows/docker.yaml'
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  generate-build-id:
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT

  push-docker-image:
    needs: [generate-build-id, unit-tests]
    uses: andreistefanciprian/gh-reusable-workflows/.github/workflows/container_image_to_dockerhub.yaml@main
    with:
      image_name: ${{ github.repository }}
      image_tag: ${{ needs.generate-build-id.outputs.BUILD_ID }}
    secrets: inherit